//this file is generated by OCAnnotation at 2019-05-10 14:28:27 +0800

#ifndef OCAnnotationAnnotationConfig_gen_h
#define OCAnnotationAnnotationConfig_gen_h

#define kOCAnnotationAnnotationConfigs @{\
@"/Users/pumpkin/Downloads/git_master/alibaba/Annotation/OCAnnotation/OCAnnotation/Example/OCAnnotation/OCAAppDelegate.m":@[\
@{\
	@"className":@"OCAAppDelegate",\
	@"position":@"method",\
	@"type":@"remoteLog",\
	@"methodSelector":@"applicationWillResignActive:",\
	@"params":@{\
		@"type":@"remoteLog",\
		@"remoteLogId":@"333456789",\
	},\
},\
],\
}
#endif 
